var beigeHeeledBoot = {
  name: "Puffy Ugly Beige Shoe",
  image: "./css/image/beige-heeled-boot.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: true,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: true,
  wedge: false,
  laces: false,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var beigeLowBootStudded = {
  name: "Spikey Balsa-Wood Heeled Boot",
  image: "./css/image/beige-low-boot-studded",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: true,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: true,
  boot: true,
  wedge: false,
  laces: false,
  studded: true,
  buckle: false,
  openToe: false,
  openHeel: false
}

var beigeOpenToeBuckleStuddedHeel = {
  name: "Impractical",
  image: "./css/image/beige-open-toe-buckle-studded-heel.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: true,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: false,
  studded: true,
  buckle: true,
  openToe: true,
  openHeel: false
}

var beigeOpenToeOpenHeelWedge = {
  name: "The Unlwalkable In",
  image: "./css/image/beige-open-toe-open-heel-wedge.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: true,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: true,
  laces: true,
  studded: false,
  buckle: false,
  openToe: true,
  openHeel: true
}

var beigeWedgeBoot = {
  name: "Tiptoe Sweat Boxes",
  image: "./css/image/beige-wedge-boot.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: true,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: true,
  laces: false,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var blackFlatBuckle = {
  name: "A Normal Black Shoe",
  image: "./css/image/black-flat-buckle.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: true,
  brown: false,
  red: false,
  flat: true,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: false,
  studded: false,
  buckle: true,
  openToe: false,
  openHeel: false
}

var blackHeelBootOpenToe = {
  name: "Walk Awkard In Black",
  image: "./css/image/black-heeled-boot-open-toe.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: true,
  brown: false,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: true,
  wedge: false,
  laces: false,
  studded: false,
  buckle: false,
  openToe: true,
  openHeel: false
}

var blackHeeledLaces = {
  name: "Impossible Heel",
  image: "./css/image/black-heeled-laces.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: true,
  brown: false,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: true,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var blackHeeledToe = {
  name: "A Long Way To Fall",
  image: "./css/image/black-heeled-toe.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: true,
  brown: false,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: false,
  studded: false,
  buckle: false,
  openToe: true,
  openHeel: false
}

var blackOpenHeel = {
  name: "Not Too Bad, Standard Black Shoe",
  image: "./css/image/black-open-heel.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: true,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: false,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var brownBuckleHeeledBoot = {
  name: "Needless Boot With Too Many Buckles",
  image: "./css/image/brown-buckle-heeled-boot.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: true,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: true,
  wedge: false,
  laces: false,
  studded: false,
  buckle: true,
  openToe: false,
  openHeel: false
}

var brownHeeledStuddedOpenToe = {
  name: "The Ball Crusher",
  image: "./css/image/brown-heeled-studded-open-toe.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: true,
  red: false,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: false,
  studded: true,
  buckle: false,
  openToe: true,
  openHeel: false
}

var brownOpenToeLaces = {
  name: "Fancy Gladiator",
  image: "./css/image/brown-open-toe-laces.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: true,
  red: false,
  flat: true,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: true,
  studded: false,
  buckle: false,
  openToe: true,
  openHeel: false
}

var brownWedge = {
  name: "Hill Walk In Style",
  image: "./css/image/brown-wedge.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: true,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: true,
  laces: false,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var redBootHeeledToe = {
  name: "Rocky Horror",
  image: "./css/image/red-boot-heeled-toe.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: false,
  red: true,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: true,
  wedge: false,
  laces: false,
  studded: false,
  buckle: false,
  openToe: true,
  openHeel: false
}

var redHeeledLaces = {
  name: "Scarlet Pimpernel",
  image: "./css/image/red-heeled-laces.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: false,
  red: true,
  flat: false,
  bigHeel: true,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: true,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var redOpenHeelBuckle = {
  name: "Dorathy's Heel",
  image: "./css/image/red-open-heel-buckle.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: false,
  red: true,
  flat: true,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: false,
  studded: false,
  buckle: true,
  openToe: false,
  openHeel: true
}

var redWedgeBoot = {
  name: "The Eddie Izzard",
  image: "./css/image/red-wedge-boot.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: false,
  red: true,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: true,
  wedge: true,
  laces: false,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var redWedge = {
  name: "Too Busy",
  image: "./css/image/red-wedge.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: false,
  beige: false,
  black: false,
  brown: false,
  red: true,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: true,
  laces: false,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var whiteFlatLaces = {
  name: "Plain Bowling Shoe",
  image: "./css/image/white-flat-laces.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: true,
  beige: false,
  black: false,
  brown: false,
  red: false,
  flat: true,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: true,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var whiteLacesOpenToeFlat = {
  name: "Missing A Few Bits",
  image: "./css/image/white-laces-open-toe-flat.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: true,
  beige: false,
  black: false,
  brown: false,
  red: false,
  flat: true,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: false,
  laces: true,
  studded: false,
  buckle: false,
  openToe: true,
  openHeel: false
}

var whiteLowLaced = {
  name: "The Dolly",
  image: "./css/image/white-low-laced.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: true,
  beige: false,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: true,
  boot: false,
  wedge: false,
  laces: true,
  studded: false,
  buckle: false,
  openToe: false,
  openHeel: false
}

var whiteLowOpenHeeledBuckle = {
  name: "They Look Fine",
  image: "./css/image/white-low-open-heeled-buckle.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: true,
  beige: false,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: true,
  boot: false,
  wedge: false,
  laces: false,
  studded: false,
  buckle: true,
  openToe: false,
  openHeel: true
}

var whiteWedgeStudded = {
  name: "Nike Gone Mad",
  image: "./css/image/white-wedge-studded.jpg",
  isYourCard: false,
  isTheirCard: false,
  isEliminated: false,
  white: true,
  beige: false,
  black: false,
  brown: false,
  red: false,
  flat: false,
  bigHeel: false,
  smallHeel: false,
  boot: false,
  wedge: true,
  laces: false,
  studded: true,
  buckle: false,
  openToe: false,
  openHeel: false
}

var opponentShoes = [ beigeHeeledBoot, beigeLowBootStudded, beigeOpenToeBuckleStuddedHeel, beigeOpenToeOpenHeelWedge, beigeWedgeBoot, blackFlatBuckle, blackHeelBootOpenToe, blackHeeledLaces, blackHeeledToe, blackOpenHeel, brownBuckleHeeledBoot, brownHeeledStuddedOpenToe, brownOpenToeLaces, brownWedge, redBootHeeledToe, redHeeledLaces, redOpenHeelBuckle, redWedgeBoot, redWedge, whiteFlatLaces, whiteLacesOpenToeFlat, whiteLowLaced, whiteLowOpenHeeledBuckle, whiteWedgeStudded ];

module.exports = opponentShoes;
